### ISSUE TITLE
The problem of  ./handover/data/compile_assets.sh

### ISSUE THREAD

**Issue by wangweifan77777** [NVlabs/handover-sim#6] opened 2023-04-17 07:00 UTC
Traceback (most recent call last):
  File "compile_mano_assets.py", line 390, in <module>
    main()
  File "compile_mano_assets.py", line 156, in main
    model = HandModel45(
TypeError: __init__() got an unexpected keyword argument 'betas'

**Comment by ychao-nvidia** [comment] 2023-04-17 14:17
Duplicate of #2 and #4

**Closed** 2023-04-22 03:48 UTC
