### ISSUE TITLE
Having a problem with compiling assets

### ISSUE THREAD

**Issue by Leon998** [NVlabs/handover-sim#4] opened 2023-01-03 13:17 UTC
When I was running `./handover/data/compile_assets.sh`, it came out with:
```
Compiling MANO assets
Traceback (most recent call last):
  File "compile_mano_assets.py", line 390, in <module>
    main()
  File "compile_mano_assets.py", line 157, in main
    left_hand=mano_side == "left", models_dir=models_dir, betas=mano_betas
TypeError: __init__() got an unexpected keyword argument 'betas'
```
It turns out that in `compile_mano_assets.py` at line 157, the model calls HandModel45 with argument 'betas'. Why does this happen and how to fix it? Thanks for answering

**Comment by ychao-nvidia** [comment] 2023-01-03 13:38
Duplicate of #2

**Comment by Leon998** [comment] 2023-01-04 02:02
Thank you very much. I didin't use SSH key to clone, so missed the [right commit](https://github.com/ychao-nvidia/mano_pybullet/commits/ac6fd6f8c01d103c52e63bb0d1d89265891738e8). Great work and thanks again

**Closed** 2023-01-04 02:03 UTC
